apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 8501
    nodePort: 31421
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Chart.Name }}
subsets:
  - addresses:
      - ip: 192.0.2.42
    ports:
      - port: 8501